//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberPortalGICWebApi.MemberAddressUpdate.cs {
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceDMLErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceRowValErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceAttrValErrorMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceErrorMessage : ServiceMessage {
        
        private object sdoObjectField;
        
        private string exceptionClassNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object sdoObject {
            get {
                return this.sdoObjectField;
            }
            set {
                this.sdoObjectField = value;
                this.RaisePropertyChanged("sdoObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string exceptionClassName {
            get {
                return this.exceptionClassNameField;
            }
            set {
                this.exceptionClassNameField = value;
                this.RaisePropertyChanged("exceptionClassName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo/java")]
    public partial class JavaInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string javaClassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string javaClass {
            get {
                return this.javaClassField;
            }
            set {
                this.javaClassField = value;
                this.RaisePropertyChanged("javaClass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public abstract partial class DataObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class Property : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] aliasNameField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private bool manyField;
        
        private bool manyFieldSpecified;
        
        private bool containmentField;
        
        private bool containmentFieldSpecified;
        
        private string defaultField;
        
        private bool readOnlyField;
        
        private bool readOnlyFieldSpecified;
        
        private string typeField;
        
        private string oppositeField;
        
        private bool nullableField;
        
        private bool nullableFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aliasName", Order=0)]
        public string[] aliasName {
            get {
                return this.aliasNameField;
            }
            set {
                this.aliasNameField = value;
                this.RaisePropertyChanged("aliasName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool many {
            get {
                return this.manyField;
            }
            set {
                this.manyField = value;
                this.RaisePropertyChanged("many");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool manySpecified {
            get {
                return this.manyFieldSpecified;
            }
            set {
                this.manyFieldSpecified = value;
                this.RaisePropertyChanged("manySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool containment {
            get {
                return this.containmentField;
            }
            set {
                this.containmentField = value;
                this.RaisePropertyChanged("containment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool containmentSpecified {
            get {
                return this.containmentFieldSpecified;
            }
            set {
                this.containmentFieldSpecified = value;
                this.RaisePropertyChanged("containmentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
                this.RaisePropertyChanged("default");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool readOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
                this.RaisePropertyChanged("readOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readOnlySpecified {
            get {
                return this.readOnlyFieldSpecified;
            }
            set {
                this.readOnlyFieldSpecified = value;
                this.RaisePropertyChanged("readOnlySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string opposite {
            get {
                return this.oppositeField;
            }
            set {
                this.oppositeField = value;
                this.RaisePropertyChanged("opposite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool nullable {
            get {
                return this.nullableField;
            }
            set {
                this.nullableField = value;
                this.RaisePropertyChanged("nullable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nullableSpecified {
            get {
                return this.nullableFieldSpecified;
            }
            set {
                this.nullableFieldSpecified = value;
                this.RaisePropertyChanged("nullableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] baseTypeField;
        
        private Property[] propertyField;
        
        private string[] aliasNameField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string uriField;
        
        private bool dataTypeField;
        
        private bool dataTypeFieldSpecified;
        
        private bool openField;
        
        private bool openFieldSpecified;
        
        private bool sequencedField;
        
        private bool sequencedFieldSpecified;
        
        private bool abstractField;
        
        private bool abstractFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("baseType", DataType="anyURI", Order=0)]
        public string[] baseType {
            get {
                return this.baseTypeField;
            }
            set {
                this.baseTypeField = value;
                this.RaisePropertyChanged("baseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property", Order=1)]
        public Property[] property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
                this.RaisePropertyChanged("property");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aliasName", Order=2)]
        public string[] aliasName {
            get {
                return this.aliasNameField;
            }
            set {
                this.aliasNameField = value;
                this.RaisePropertyChanged("aliasName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("dataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataTypeSpecified {
            get {
                return this.dataTypeFieldSpecified;
            }
            set {
                this.dataTypeFieldSpecified = value;
                this.RaisePropertyChanged("dataTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
                this.RaisePropertyChanged("open");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool openSpecified {
            get {
                return this.openFieldSpecified;
            }
            set {
                this.openFieldSpecified = value;
                this.RaisePropertyChanged("openSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool sequenced {
            get {
                return this.sequencedField;
            }
            set {
                this.sequencedField = value;
                this.RaisePropertyChanged("sequenced");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequencedSpecified {
            get {
                return this.sequencedFieldSpecified;
            }
            set {
                this.sequencedFieldSpecified = value;
                this.RaisePropertyChanged("sequencedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @abstract {
            get {
                return this.abstractField;
            }
            set {
                this.abstractField = value;
                this.RaisePropertyChanged("abstract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool abstractSpecified {
            get {
                return this.abstractFieldSpecified;
            }
            set {
                this.abstractFieldSpecified = value;
                this.RaisePropertyChanged("abstractSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class ChangeSummaryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private string createField;
        
        private string deleteField;
        
        private bool loggingField;
        
        private bool loggingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string create {
            get {
                return this.createField;
            }
            set {
                this.createField = value;
                this.RaisePropertyChanged("create");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
                this.RaisePropertyChanged("delete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool logging {
            get {
                return this.loggingField;
            }
            set {
                this.loggingField = value;
                this.RaisePropertyChanged("logging");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loggingSpecified {
            get {
                return this.loggingFieldSpecified;
            }
            set {
                this.loggingFieldSpecified = value;
                this.RaisePropertyChanged("loggingSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class XSDType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class ModelsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataGraphType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public abstract partial class BaseDataGraphType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ModelsType modelsField;
        
        private XSDType xsdField;
        
        private ChangeSummaryType changeSummaryField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ModelsType models {
            get {
                return this.modelsField;
            }
            set {
                this.modelsField = value;
                this.RaisePropertyChanged("models");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public XSDType xsd {
            get {
                return this.xsdField;
            }
            set {
                this.xsdField = value;
                this.RaisePropertyChanged("xsd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ChangeSummaryType changeSummary {
            get {
                return this.changeSummaryField;
            }
            set {
                this.changeSummaryField = value;
                this.RaisePropertyChanged("changeSummary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class DataGraphType : BaseDataGraphType {
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceDMLErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceRowValErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceAttrValErrorMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string severityField;
        
        private ServiceMessage[] detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detail", Order=3)]
        public ServiceMessage[] detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LifeAddressResponseSDO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="/com/mni/mednext/services/model/enrolment/queries/common/")]
    public partial class LifeAddressRequestSDO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> memberNumberField;
        
        private bool memberNumberFieldSpecified;
        
        private string addressTypeIdField;
        
        private string mailingIndicatorField;
        
        private string addressTextField;
        
        private string zipCodeField;
        
        private string poBoxField;
        
        private string countryCodeField;
        
        private string regionCodeField;
        
        private string districtCodeField;
        
        private string administrativeUnitCodeField;
        
        private string cityCodeField;
        
        private string phoneNumber1Field;
        
        private string phoneNumber2Field;
        
        private string phoneNumber3Field;
        
        private string phoneNumber4Field;
        
        private string email1Field;
        
        private string email2Field;
        
        private string faxNumberField;
        
        private string websiteURLField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> MemberNumber {
            get {
                return this.memberNumberField;
            }
            set {
                this.memberNumberField = value;
                this.RaisePropertyChanged("MemberNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MemberNumberSpecified {
            get {
                return this.memberNumberFieldSpecified;
            }
            set {
                this.memberNumberFieldSpecified = value;
                this.RaisePropertyChanged("MemberNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string AddressTypeId {
            get {
                return this.addressTypeIdField;
            }
            set {
                this.addressTypeIdField = value;
                this.RaisePropertyChanged("AddressTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string MailingIndicator {
            get {
                return this.mailingIndicatorField;
            }
            set {
                this.mailingIndicatorField = value;
                this.RaisePropertyChanged("MailingIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string AddressText {
            get {
                return this.addressTextField;
            }
            set {
                this.addressTextField = value;
                this.RaisePropertyChanged("AddressText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string PoBox {
            get {
                return this.poBoxField;
            }
            set {
                this.poBoxField = value;
                this.RaisePropertyChanged("PoBox");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string RegionCode {
            get {
                return this.regionCodeField;
            }
            set {
                this.regionCodeField = value;
                this.RaisePropertyChanged("RegionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string DistrictCode {
            get {
                return this.districtCodeField;
            }
            set {
                this.districtCodeField = value;
                this.RaisePropertyChanged("DistrictCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string AdministrativeUnitCode {
            get {
                return this.administrativeUnitCodeField;
            }
            set {
                this.administrativeUnitCodeField = value;
                this.RaisePropertyChanged("AdministrativeUnitCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string CityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("CityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string PhoneNumber1 {
            get {
                return this.phoneNumber1Field;
            }
            set {
                this.phoneNumber1Field = value;
                this.RaisePropertyChanged("PhoneNumber1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string PhoneNumber2 {
            get {
                return this.phoneNumber2Field;
            }
            set {
                this.phoneNumber2Field = value;
                this.RaisePropertyChanged("PhoneNumber2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string PhoneNumber3 {
            get {
                return this.phoneNumber3Field;
            }
            set {
                this.phoneNumber3Field = value;
                this.RaisePropertyChanged("PhoneNumber3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string PhoneNumber4 {
            get {
                return this.phoneNumber4Field;
            }
            set {
                this.phoneNumber4Field = value;
                this.RaisePropertyChanged("PhoneNumber4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string Email1 {
            get {
                return this.email1Field;
            }
            set {
                this.email1Field = value;
                this.RaisePropertyChanged("Email1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string Email2 {
            get {
                return this.email2Field;
            }
            set {
                this.email2Field = value;
                this.RaisePropertyChanged("Email2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
                this.RaisePropertyChanged("FaxNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string WebsiteURL {
            get {
                return this.websiteURLField;
            }
            set {
                this.websiteURLField = value;
                this.RaisePropertyChanged("WebsiteURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="/com/mni/mednext/services/model/enrolment/queries/common/")]
    public partial class LifeAddressResponseSDO : LifeAddressRequestSDO {
        
        private System.Nullable<decimal> addressNumberField;
        
        private bool addressNumberFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> AddressNumber {
            get {
                return this.addressNumberField;
            }
            set {
                this.addressNumberField = value;
                this.RaisePropertyChanged("AddressNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressNumberSpecified {
            get {
                return this.addressNumberFieldSpecified;
            }
            set {
                this.addressNumberFieldSpecified = value;
                this.RaisePropertyChanged("AddressNumberSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceDMLErrorMessage : ServiceErrorMessage {
        
        private string operationField;
        
        private string statementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statement {
            get {
                return this.statementField;
            }
            set {
                this.statementField = value;
                this.RaisePropertyChanged("statement");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceRowValErrorMessage : ServiceErrorMessage {
        
        private string objectNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string objectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("objectName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceAttrValErrorMessage : ServiceErrorMessage {
        
        private string attributeNameField;
        
        private string attributeValueField;
        
        private string objectNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
                this.RaisePropertyChanged("attributeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string attributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
                this.RaisePropertyChanged("attributeValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string objectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("objectName");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="/com/mni/mednext/services/model/enrolment/modules/common/", ConfigurationName="MemberAddressUpdate.cs.LifeAdressDS")]
    public interface LifeAdressDS {
        
        // CODEGEN: Generating message contract since the wrapper namespace (/com/mni/mednext/services/model/enrolment/modules/common/types/) of message createLifeAddressRequest does not match the default value (/com/mni/mednext/services/model/enrolment/modules/common/)
        [System.ServiceModel.OperationContractAttribute(Action="/com/mni/mednext/services/model/enrolment/modules/common/createLifeAddress", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MemberPortalGICWebApi.MemberAddressUpdate.cs.ServiceErrorMessage), Action="/com/mni/mednext/services/model/enrolment/modules/common/createLifeAddress", Name="ServiceErrorMessage", Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JavaInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseDataGraphType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceMessage))]
        MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressResponse createLifeAddress(MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/com/mni/mednext/services/model/enrolment/modules/common/createLifeAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressResponse> createLifeAddressAsync(MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (/com/mni/mednext/services/model/enrolment/modules/common/types/) of message updateLifeAddressRequest does not match the default value (/com/mni/mednext/services/model/enrolment/modules/common/)
        [System.ServiceModel.OperationContractAttribute(Action="/com/mni/mednext/services/model/enrolment/modules/common/updateLifeAddress", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MemberPortalGICWebApi.MemberAddressUpdate.cs.ServiceErrorMessage), Action="/com/mni/mednext/services/model/enrolment/modules/common/updateLifeAddress", Name="ServiceErrorMessage", Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JavaInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseDataGraphType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceMessage))]
        MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressResponse updateLifeAddress(MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/com/mni/mednext/services/model/enrolment/modules/common/updateLifeAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressResponse> updateLifeAddressAsync(MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (/com/mni/mednext/services/model/enrolment/modules/common/types/) of message deleteLifeAddressRequest does not match the default value (/com/mni/mednext/services/model/enrolment/modules/common/)
        [System.ServiceModel.OperationContractAttribute(Action="/com/mni/mednext/services/model/enrolment/modules/common/deleteLifeAddress", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MemberPortalGICWebApi.MemberAddressUpdate.cs.ServiceErrorMessage), Action="/com/mni/mednext/services/model/enrolment/modules/common/deleteLifeAddress", Name="ServiceErrorMessage", Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JavaInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseDataGraphType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceMessage))]
        MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressResponse deleteLifeAddress(MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/com/mni/mednext/services/model/enrolment/modules/common/deleteLifeAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressResponse> deleteLifeAddressAsync(MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createLifeAddress", WrapperNamespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", IsWrapped=true)]
    public partial class createLifeAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", Order=0)]
        public MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressRequestSDO row;
        
        public createLifeAddressRequest() {
        }
        
        public createLifeAddressRequest(MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressRequestSDO row) {
            this.row = row;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createLifeAddressResponse", WrapperNamespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", IsWrapped=true)]
    public partial class createLifeAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", Order=0)]
        public MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressResponseSDO result;
        
        public createLifeAddressResponse() {
        }
        
        public createLifeAddressResponse(MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressResponseSDO result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateLifeAddress", WrapperNamespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", IsWrapped=true)]
    public partial class updateLifeAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", Order=0)]
        public MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressRequestSDO row;
        
        public updateLifeAddressRequest() {
        }
        
        public updateLifeAddressRequest(MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressRequestSDO row) {
            this.row = row;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateLifeAddressResponse", WrapperNamespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", IsWrapped=true)]
    public partial class updateLifeAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", Order=0)]
        public MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressResponseSDO result;
        
        public updateLifeAddressResponse() {
        }
        
        public updateLifeAddressResponse(MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressResponseSDO result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteLifeAddress", WrapperNamespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", IsWrapped=true)]
    public partial class deleteLifeAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", Order=0)]
        public decimal MemberNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", Order=1)]
        public string AddressTypeId;
        
        public deleteLifeAddressRequest() {
        }
        
        public deleteLifeAddressRequest(decimal MemberNumber, string AddressTypeId) {
            this.MemberNumber = MemberNumber;
            this.AddressTypeId = AddressTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteLifeAddressResponse", WrapperNamespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", IsWrapped=true)]
    public partial class deleteLifeAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="/com/mni/mednext/services/model/enrolment/modules/common/types/", Order=0)]
        public MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressResponseSDO result;
        
        public deleteLifeAddressResponse() {
        }
        
        public deleteLifeAddressResponse(MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressResponseSDO result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LifeAdressDSChannel : MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LifeAdressDSClient : System.ServiceModel.ClientBase<MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS>, MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS {
        
        public LifeAdressDSClient() {
        }
        
        public LifeAdressDSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LifeAdressDSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LifeAdressDSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LifeAdressDSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressResponse MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS.createLifeAddress(MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressRequest request) {
            return base.Channel.createLifeAddress(request);
        }
        
        public MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressResponseSDO createLifeAddress(MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressRequestSDO row) {
            MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressRequest inValue = new MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressRequest();
            inValue.row = row;
            MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressResponse retVal = ((MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS)(this)).createLifeAddress(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressResponse> MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS.createLifeAddressAsync(MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressRequest request) {
            return base.Channel.createLifeAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressResponse> createLifeAddressAsync(MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressRequestSDO row) {
            MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressRequest inValue = new MemberPortalGICWebApi.MemberAddressUpdate.cs.createLifeAddressRequest();
            inValue.row = row;
            return ((MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS)(this)).createLifeAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressResponse MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS.updateLifeAddress(MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressRequest request) {
            return base.Channel.updateLifeAddress(request);
        }
        
        public MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressResponseSDO updateLifeAddress(MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressRequestSDO row) {
            MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressRequest inValue = new MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressRequest();
            inValue.row = row;
            MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressResponse retVal = ((MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS)(this)).updateLifeAddress(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressResponse> MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS.updateLifeAddressAsync(MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressRequest request) {
            return base.Channel.updateLifeAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressResponse> updateLifeAddressAsync(MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressRequestSDO row) {
            MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressRequest inValue = new MemberPortalGICWebApi.MemberAddressUpdate.cs.updateLifeAddressRequest();
            inValue.row = row;
            return ((MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS)(this)).updateLifeAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressResponse MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS.deleteLifeAddress(MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressRequest request) {
            return base.Channel.deleteLifeAddress(request);
        }
        
        public MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAddressResponseSDO deleteLifeAddress(decimal MemberNumber, string AddressTypeId) {
            MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressRequest inValue = new MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressRequest();
            inValue.MemberNumber = MemberNumber;
            inValue.AddressTypeId = AddressTypeId;
            MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressResponse retVal = ((MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS)(this)).deleteLifeAddress(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressResponse> MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS.deleteLifeAddressAsync(MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressRequest request) {
            return base.Channel.deleteLifeAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressResponse> deleteLifeAddressAsync(decimal MemberNumber, string AddressTypeId) {
            MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressRequest inValue = new MemberPortalGICWebApi.MemberAddressUpdate.cs.deleteLifeAddressRequest();
            inValue.MemberNumber = MemberNumber;
            inValue.AddressTypeId = AddressTypeId;
            return ((MemberPortalGICWebApi.MemberAddressUpdate.cs.LifeAdressDS)(this)).deleteLifeAddressAsync(inValue);
        }
    }
}
